export { default as Facebook } from './Facebook'
export { default as Instagram } from './Instagram'
export { default as Linkedin } from './Linkedin'
export { default as Pinterest } from './Pinterest'
export { default as Tiktok } from './Tiktok'
export { default as Twitter } from './Twitter'
export { default as Youtube } from './Youtube'
